version: "3.7"

services:
  mongo:
    image: 'mongo:3'
    expose:
      - '27017'

  rabbitmq:
    image: 'rabbitmq:3'
    hostname: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=tapiriik

  redis:
    image: 'redis:3'
    # Fix WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128
    # https://github.com/docker-library/redis/issues/35
    sysctls:
      net.core.somaxconn: '511'

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    command:
      - manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - '8000:${PORT:-8000}'

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    command:
      - sync_worker.py
    # The worker shuts down after completing n tasks so restart on exit
    # https://github.com/cpfair/tapiriik/issues/191#issuecomment-164065625
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    command:
      - sync_scheduler.py
